### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(CardReaderContent)
add_subdirectory(CardReader)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    CardReaderContentplugin
    CardReaderplugin)